In [1]:
import pandas as pd
import os

In [2]:
from functions.get_btc import *

In [3]:
df_btc = btc().copy()

In [4]:
# Dl datos csv
# Make correlation

In [5]:
# import required module
csvs =[]
# assign directory
directory = 'data/datos'

# iterate over files in
# that directory
for filename in os.listdir(directory):
    csvs.append(filename[:-4])

In [6]:
csvs

['btc',
 'dxy',
 'merged_addresses_active_count',
 'merged_addresses_new_non_zero_count',
 'merged_balances',
 'merged_fees_volume_sum',
 'merged_indicators_sopr',
 'merged_indicators_stock_to_flow_ratio',
 'merged_institutions_purpose_etf_aum_sum',
 'merged_institutions_purpose_etf_flows_sum',
 'merged_institutions_purpose_etf_holdings_sum',
 'merged_M2s',
 'merged_market_marketcap_usd',
 'merged_supply_active_more_1y_percent',
 'merged_transactions_count',
 'merged_transactions_size_mean',
 'Mining_Hashrate',
 'Mining_Total Transaction Fees (BTC)',
 'On-Chain_unique-addresses']

In [7]:
df = pd.DataFrame(csvs)

In [8]:
df.columns = ['names']

In [9]:
df

                                           names
0                                            btc
1                                            dxy
2                  merged_addresses_active_count
3            merged_addresses_new_non_zero_count
4                                merged_balances
5                         merged_fees_volume_sum
6                         merged_indicators_sopr
7          merged_indicators_stock_to_flow_ratio
8        merged_institutions_purpose_etf_aum_sum
9      merged_institutions_purpose_etf_flows_sum
10  merged_institutions_purpose_etf_holdings_sum
11                                    merged_M2s
12                   merged_market_marketcap_usd
13          merged_supply_active_more_1y_percent
14                     merged_transactions_count
15                 merged_transactions_size_mean
16                               Mining_Hashrate
17           Mining_Total Transaction Fees (BTC)
18                     On-Chain_unique-addresses

In [10]:
# corr raw, corr z, corr z in 50.

In [23]:
dic = {}
for e in csvs:
    name = f'{e}_df'
    name = pd.read_csv(f'data\datos\{e}.csv')
    
    try: 
        dic[e]=name[['Close','metric']].corr().iloc[0,1]   
    except:
        print(e, ': not available')

btc : not available
dxy : not available
merged_balances : not available
merged_M2s : not available

In [24]:
dic['merged_M2s']= 0.8341512979642502

In [25]:
dxy = pd.read_csv(f'data\datos\dxy.csv')
dxy = dxy[['Date', 'Close']]
dxy.columns=['Date','metric']

In [26]:
dxy = df_btc.merge(dxy, left_index = True, right_on= 'Date')

In [27]:
dic['dxy']=dxy[['Close','metric']].corr().iloc[0,1]

In [28]:
dic

{'merged_addresses_active_count': 0.7041169393663363,
 'merged_addresses_new_non_zero_count': 0.6356823373061199,
 'merged_fees_volume_sum': -0.02393825402169299,
 'merged_indicators_sopr': 0.06470514154175576,
 'merged_indicators_stock_to_flow_ratio': 0.8604043693361753,
 'merged_institutions_purpose_etf_aum_sum': 0.7371657003316816,
 'merged_institutions_purpose_etf_flows_sum': 0.052865545503067435,
 'merged_institutions_purpose_etf_holdings_sum': -0.2374984753392627,
 'merged_market_marketcap_usd': 0.9998465171520863,
 'merged_supply_active_more_1y_percent': 0.3625094766659469,
 'merged_transactions_count': 0.4640914028383881,
 'merged_transactions_size_mean': 0.5536486709623619,
 'Mining_Hashrate': 0.7545137361364878,
 'Mining_Total Transaction Fees (BTC)': -0.02463970469218787,
 'On-Chain_unique-addresses': 0.6786323500499182,
 'merged_M2s': 0.8341512979642502,
 'dxy': 0.2857330759829787}

In [29]:
#add balances

In [30]:
balances = pd.read_csv(f'data\datos\merged_balances.csv')

In [31]:
balances = balances.iloc[:,1:]

In [32]:
balances

,Close,High,Low,Open,Volume,date,totalVolume_less_than_0_01,addressesCount_less_than_0_01,totalVolume_f_0_01_to_0_1,addressesCount_f_0_01_to_0_1,...,totalVolume_f_1_to_10,addressesCount_f_1_to_10,totalVolume_f_10_to_100,addressesCount_f_10_to_100,totalVolume_f_100_to_1000,addressesCount_f_100_to_1000,totalVolume_f_1000_to_10000,addressesCount_f_1000_to_10000,totalVolume_f_10000_to_100000,addressesCount_f_10000_to_100000
0,4164.82,4227.62,4022.02,4183.47,12191.930651,2017-09-29,16312.999555,15343269.0,87887.392119,2816078.0,...,1.315085e+06,482521.0,2.998753e+06,104998.0,3.871631e+06,16578.0,3.513604e+06,1617.0,2.839909e+06,116.0
1,4326.09,4349.00,4154.28,4162.04,7496.782499,2017-09-30,16363.437837,15359725.0,88113.314124,2822795.0,...,1.314929e+06,482580.0,2.999890e+06,105012.0,3.872885e+06,16568.0,3.500371e+06,1616.0,2.853719e+06,117.0
2,4377.22,4377.22,4216.00,4326.09,7211.335136,2017-10-01,16420.769989,15349350.0,88338.100340,2829325.0,...,1.315660e+06,482902.0,3.000484e+06,105072.0,3.877193e+06,16583.0,3.496888e+06,1612.0,2.855150e+06,117.0
3,4391.48,4453.00,4352.00,4369.33,8259.818632,2017-10-02,16408.116688,15362789.0,88655.206332,2836046.0,...,1.318321e+06,484200.0,3.002632e+06,105088.0,3.868918e+06,16544.0,3.499731e+06,1612.0,2.755759e+06,116.0
4,4315.83,4425.00,4218.00,4391.41,12468.057256,2017-10-03,16495.852412,15376591.0,88935.478118,2844895.0,...,1.320843e+06,485267.0,3.002938e+06,105180.0,3.853082e+06,16511.0,3.500202e+06,1616.0,2.765938e+06,117.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2743,25050.00,25217.00,24229.00,24361.00,2430.850193,2023-03-16,44221.860339,33609770.0,249303.239238,7413604.0,...,2.076512e+06,830941.0,4.437565e+06,139897.0,3.927446e+06,14088.0,4.553420e+06,1905.0,2.348874e+06,111.0
2744,27466.00,27818.00,24954.00,25051.00,5166.282770,2023-03-17,44242.362864,33658045.0,249060.142721,7404254.0,...,2.076336e+06,830944.0,4.432055e+06,139743.0,3.932888e+06,14097.0,4.555905e+06,1910.0,2.347687e+06,111.0
2745,26980.00,27776.00,26707.00,27466.00,2933.796863,2023-03-18,44292.208899,33688934.0,249095.867904,7404877.0,...,2.074852e+06,830732.0,4.432100e+06,139716.0,3.927460e+06,14074.0,4.558987e+06,1911.0,2.352962e+06,111.0
2746,28054.00,28474.00,26900.00,26992.00,2615.712518,2023-03-19,44373.329217,33742543.0,249108.450222,7405136.0,...,2.075353e+06,830996.0,4.432360e+06,139716.0,3.928109e+06,14083.0,4.554001e+06,1913.0,2.356884e+06,112.0
2747,27815.00,28567.00,27231.00,28081.00,3998.093582,2023-03-20,44247.868484,33751423.0,249137.355997,7405989.0,...,2.075765e+06,831145.0,4.432921e+06,139770.0,3.923831e+06,14071.0,4.566517e+06,1916.0,2.318242e+06,111.0

In [36]:
# for addresses

bal_dic=  {'<0.01':'less_than_0_01', '0.01 - 0.1': 'f_0_01_to_0_1' ,'0.1 - 1': 'f_0_1_to_1', '1 - 10' : 'f_1_to_10', '10 - 100' : 'f_10_to_100','100 - 1000' : 'f_100_to_1000', '1k - 10k' : 'f_1000_to_10000','10k+' : 'f_10000_to_100000'}

for e in bal_dic.values():
    ind = 'addressesCount_' + e
    dic[ind]=balances[['Close',ind]].corr().iloc[0,1]

In [37]:
# for Volume
for e in bal_dic.values():
    ind = 'totalVolume_' + e
    dic[ind]=balances[['Close',ind]].corr().iloc[0,1]

In [38]:
dic

{'merged_addresses_active_count': 0.7041169393663363,
 'merged_addresses_new_non_zero_count': 0.6356823373061199,
 'merged_fees_volume_sum': -0.02393825402169299,
 'merged_indicators_sopr': 0.06470514154175576,
 'merged_indicators_stock_to_flow_ratio': 0.8604043693361753,
 'merged_institutions_purpose_etf_aum_sum': 0.7371657003316816,
 'merged_institutions_purpose_etf_flows_sum': 0.052865545503067435,
 'merged_institutions_purpose_etf_holdings_sum': -0.2374984753392627,
 'merged_market_marketcap_usd': 0.9998465171520863,
 'merged_supply_active_more_1y_percent': 0.3625094766659469,
 'merged_transactions_count': 0.4640914028383881,
 'merged_transactions_size_mean': 0.5536486709623619,
 'Mining_Hashrate': 0.7545137361364878,
 'Mining_Total Transaction Fees (BTC)': -0.02463970469218787,
 'On-Chain_unique-addresses': 0.6786323500499182,
 'merged_M2s': 0.8341512979642502,
 'dxy': 0.2857330759829787,
 'addressesCount_less_than_0_01': 0.7309208751791545,
 'addressesCount_f_0_01_to_0_1': 0.5637098421342339,
 'addressesCount_f_0_1_to_1': 0.49074004934346577,
 'addressesCount_f_1_to_10': 0.39971240634897914,
 'addressesCount_f_10_to_100': 0.7220104070034703,
 'addressesCount_f_100_to_1000': -0.4696891694979818,
 'addressesCount_f_1000_to_10000': 0.5882112032070773,
 'addressesCount_f_10000_to_100000': -0.814401293882881,
 'totalVolume_less_than_0_01': 0.7129026325946831,
 'totalVolume_f_0_01_to_0_1': 0.5425804929859651,
 'totalVolume_f_0_1_to_1': 0.47681921331725013,
 'totalVolume_f_1_to_10': 0.34252539623862066,
 'totalVolume_f_10_to_100': 0.7733483844107766,
 'totalVolume_f_100_to_1000': 0.6735545424484679,
 'totalVolume_f_1000_to_10000': 0.5943557723662132,
 'totalVolume_f_10000_to_100000': -0.601373294249351}

In [ ]:
#Add a comparative with index of bank's stocks